development:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: makersbnb
  pool: 2
